# ========== Image Upload - Local Windows ==========
building.image.upload-dir=D:/study/code/javaProgramming/estate-management/src/main/resources/static/images/building_img
staff.image.upload-dir=D:/study/code/javaProgramming/estate-management/src/main/resources/static/images/staff_img

# ========== Image Upload - Cloudinary (No need for local) ==========
cloudinary.cloud-name=dummy
cloudinary.api-key=dummy
cloudinary.api-secret=dummy

# ========== VNPay return URL - Local (ngrok) ==========
vnpay.return-url=https://estela-unlopped-leroy.ngrok-free.dev/payment/vnpay-return