# ========== Image Upload - Cloudinary ==========
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ========== VNPay return URL - Local (ngrok) ==========
vnpay.return-url=https://estela-unlopped-leroy.ngrok-free.dev/payment/vnpay-return