# ========== General Spring Configuration ==========
spring.application.name=EstateManagementSystem

# ========== Thymeleaf Configuration ==========
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# ========== Active Database Configuration ==========
spring.profiles.active=mysql

# ========== JPA Configuration ==========
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# ========== Email Configuration ==========
spring.mail.host=smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=b8356893382458
spring.mail.password=2ff0e1ddef037a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ========== VNPay Sandbox ==========
vnpay.tmn-code=9E5CIVXU
vnpay.hash-secret=4IG2O6N6KNX8AXK1NJ5PQGE6I13NPXRO
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=https://estela-unlopped-leroy.ngrok-free.dev/payment/vnpay-return

# ========== Real Estate Image Upload ==========
# Directory path to store uploaded building images
# (On Windows, use / instead of \ )
building.image.upload-dir=D:/study/code/javaProgramming/estate-management/src/main/resources/static/images/building_img

# Multipart file upload size limit (5MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# ========== Goong Maps API ==========
goong.api.key=MfQYQasRyhJp6OkpEOlOAW8GwrhVgz043MK0WDvx