# ========== Image Upload - Cloudinary ==========
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ========== VNPay return URL - Railway ==========
vnpay.return-url=${VNPAY_RETURN_URL}

# ========== Cookie secure on HTTPS ==========
jwt.cookie-secure=false

# Decrease connection pool to minimum
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000