# Khi chạy trong Docker, trỏ đến service "db" thay vì localhost
spring.datasource.url=jdbc:mysql://db:3306/estate?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

vnpay.return-url=http://localhost:8080/payment/vnpay-return
jwt.cookie-secure=false